layout_spectrum: 0.7394234697442355
typography_spectrum: 0.5507427270745509
color:
  brandStrength: 0.6131309634364108
  lightness: 0.667600081598128
  saturation: 0.8867703559081818
  rhythmicContrast: 1
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Granite State Craft Works
content: []
title: Granite State Craft Works
description: ''
github: true
